/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\theme\cosmoTheme.ts
 * Command: astryx theme build app\theme\cosmoTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./cosmo.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const cosmoTheme: DefinedTheme;
