/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\theme\cosmoTheme.ts
 * Command: astryx theme build app\theme\cosmoTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
